import numpy as np
import pandas as pd

from models.thermal_2r2c import Thermal2R2CPredictor


def test_fit_predict():
    rng = np.random.default_rng(42)

    n = 100

    T_out = 10 + rng.normal(scale=2.0, size=n)

    true_theta = [
        2.0,     # R_ow
        0.5,     # R_iw
        5e5,     # C_w
        5e4,     # C_a
        20.0,    # T_wall0
    ]

    T_air = Thermal2R2CPredictor._simulate(
        true_theta,
        T_out,
        T_air0=20.0,
    )

    X = pd.DataFrame(
        {
            "temp_out": T_out,
            "temp_in": np.full(n, 20.0),
        }
    )

    model = Thermal2R2CPredictor()
    model.fit(X, T_air)

    preds = model.predict(X)

    assert preds.shape == T_air.shape

    # Since the data were generated by the same model,
    # the fitted trajectory should be very close.
    np.testing.assert_allclose(preds, T_air, atol=1e-2)


def test_save_and_load(tmp_path):
    rng = np.random.default_rng(42)

    n = 100

    T_out = 10 + rng.normal(scale=2.0, size=n)

    true_theta = [
        2.0,
        0.5,
        5e5,
        5e4,
        20.0,
    ]

    T_air = Thermal2R2CPredictor._simulate(
        true_theta,
        T_out,
        T_air0=20.0,
    )

    X = pd.DataFrame(
        {
            "temp_out": T_out,
            "temp_in": np.full(n, 20.0),
        }
    )

    model = Thermal2R2CPredictor()
    model.fit(X, T_air)

    expected = model.predict(X)

    model.save(tmp_path)

    loaded_model = Thermal2R2CPredictor.load(tmp_path)

    actual = loaded_model.predict(X)

    np.testing.assert_allclose(actual, expected, atol=1e-10)